Use https://github.com/ptr33/knxd.git instead of knx/knxd.git
Update eibtypes.h fix compiler error
#14 45.04 ../../../src/include/eibtypes.h:90:1: error: C++ style comments are not allowed in ISO C90